### ISSUE TITLE
Project paths for beaengine are absolute

### ISSUE THREAD

**Issue by Resaec** [dude719/Reclass-2015#11]
The projectpaths for beaengine are absolute
(C:\Users\Owner\...)

They should be relative to the project
(..\beaengine\...)

**Comment by Timboy67678** [comment]
both libraries are precompiled and included in the git, i will change these for people who need to recompile them but its a non-issue atm

**Comment by dude719** [comment]
How is this a bug? Most projects don't even include the library dependencies and expect the dev to know what they're doing. It's not a bug, or an issue,

**Comment by Timboy67678** [comment]
i thought i had removed the bug label, my bad
