### ISSUE TITLE
Text is too small on high DPI screens

### ISSUE THREAD

**Issue by jocopa3** [dude719/Reclass-2015#13]
I'm currently using a 4K monitor as my daily driver. In previous versions of ReClass Windows would simply scale the program and text was better readible albeit slightly blurry. However, in the newer releases, Windows no longer scales the program and text looks much smaller. I've been using an older build of ReClass as there's no DPI scaling or options to adjust text size in the newer builds.

For comparison, below is text in ReClass compared to the normal text size in Windows. Text in the ribbon looks fine, though text in the memory/class view is roughly two times smaller than regular text.
![Normal text vs Reclass](http://i.imgur.com/fznKnJs.png)

**Comment by Timboy67678** [comment]
what about the generate window, does that scale with dpi? scintilla mustn't be high-dpi aware. Its going to be difficult to fix and diagnose as i don't have a 4k monitor to test with for higher dpi, but ill see what i can do

**Comment by jocopa3** [comment]
The generate window looks fine. The only window that's too small is the memory view.

You can change DPI settings in Windows which would help with testing. On Windows 10, you can set scaling in display settings which has the same effect as increasing the DPI. In Windows 7 there is an option in control panel to set text size which also changes the DPI.

**Comment by Timboy67678** [comment]
Cant find a reason as to why scintilla wouldnt scale, gonna see if @dude719 has ian idea

**Comment by Timboy67678** [comment]
@jocopa3 let me know if its fixed or not

**Comment by jocopa3** [comment]
It's fixed. Thanks for looking into the issue. Would be nice if there was a CTRL+Scroll feature to change text size.

**Comment by Timboy67678** [comment]
no problem, ill close this issue and if you can go ahead and make another issue ill mark it as enhancement for our backlog of shit to add
