### ISSUE TITLE
Huge memory leak at Win8 x64

### ISSUE THREAD

**Issue by lastblade** [dude719/Reclass-2015#14]
![screenshot 3](https://cloud.githubusercontent.com/assets/11603980/16709708/9fcb8840-45ee-11e6-8f6d-73a300e14d98.png)

**Comment by dude719** [comment]
Oops. Let me look into that.

**Comment by Timboy67678** [comment]
do you have any information? like how it is you got to this point?

**Comment by lastblade** [comment]
well, im using with bf4. i happens mostly is less than a hour after i opened. 
i can provide my reclass file if it helps.

**Comment by dude719** [comment]
Can you screenshot what is in the ReClass Console Log?

**Comment by lastblade** [comment]
![image](https://cloud.githubusercontent.com/assets/11603980/16739939/eabac818-4772-11e6-9daa-d723e04fb176.png)

You're right. it's the console.

**Comment by dude719** [comment]
Made a work around for the overflow by removing that error message. Should be okay now.
