### ISSUE TITLE
Weird bug when fixing classes

### ISSUE THREAD

**Issue by lastblade** [dude719/Reclass-2015#15]
![g3mvmp4 1](https://cloud.githubusercontent.com/assets/11603980/16972928/ae151bb8-4e05-11e6-8f80-f0d506b4b815.gif)

it happens mostly with newly made classes

**Comment by Timboy67678** [comment]
So many classes, it might be due to the massive size of classes. ill take a look

**Comment by lastblade** [comment]
Great. Btw, there is any option to delete Classes ? i couldn't find

**Comment by Timboy67678** [comment]
at the top there is a delete button, you can use that to delete classes
![image](https://cloud.githubusercontent.com/assets/994534/17076804/67033104-50ff-11e6-8d70-0d7a40841605.png)

Sorry for the late reply, been busy doing some other things. ill take a look at both this and #16

**Comment by dude719** [comment]
I started making a dialog for deleting classes, right now its total shit. I'll work on it when I find time.

**Comment by dude719** [comment]
Oh yeah, also the max classes right now is 128 or 256, cant remember, but its more than that it'll mess up.

**Comment by Timboy67678** [comment]
enhancement for increasing max class size.

**Comment by Timboy67678** [comment]
fixed with commit: https://github.com/dude719/Reclass-2015/commit/076107fbde215efb7bcae53dfd874f925115a749
