### ISSUE TITLE
App crash when we create a text item [1024 or bigger]

### ISSUE THREAD

**Issue by lastblade** [dude719/Reclass-2015#16]
![image](https://cloud.githubusercontent.com/assets/11603980/17033395/53b221f2-4f54-11e6-8485-6f735f58a4c1.png)

**Comment by Timboy67678** [comment]
Investigating... how big is that text array before you edited it to put in 1024?

**Comment by Timboy67678** [comment]
Found the bug, i'm gonna issue a fix soon

**Comment by Timboy67678** [comment]
http://i.imgur.com/E4zZWoT.png

**Comment by dude719** [comment]
Lol yeah this has been an issue for months, was lazy to fix it and kept forgetting.
