### ISSUE TITLE
not work in win7

### ISSUE THREAD

**Issue by huangfengye** [dude719/Reclass-2015#17]
last source not work in win7..

**Comment by Timboy67678** [comment]
what do you mean not work? can you give me any more details?

**Comment by huangfengye** [comment]
i Compile it, and it can run in win10, but can;t run in win7
missing dll api-ms-win-shcore-scaling-l1-1-1.dll 
after i add dll to system.
it show this.
http://puu.sh/qomfr/921b3625db.png

**Comment by Timboy67678** [comment]
sounds like your windows 7 doesnt have the universal CRT update (https://support.microsoft.com/en-au/kb/2999226). Try seeing if that (or the vs2015 redistributable) works for you. this isn't a project related problem and is user specific.

**Comment by huangfengye** [comment]
i had install vs2015, and it should be include universal CRT update

**Comment by huangfengye** [comment]
my win7 have  the universal CRT update!!!
i install vs2015 in win7 too....

**Comment by dude719** [comment]
That DLL might be part of the Windows 10 SDK. Ill take a look at what exports are used from that DLL and see if I can come up with a work around.

**Comment by dude719** [comment]
Alternatively, you can try using an earlier compiler, but that could be a giant pain in the ass.
