### ISSUE TITLE
QWord

### ISSUE THREAD

**Issue by Forsari0** [dude719/Reclass-2015#18]
If this is x64 incarnation of REclass, where is one of the most important **QWord** _(8 bytes unsigned)_ type?
Am I missing something?

**Comment by Timboy67678** [comment]
must have forgotten to add it, use int64 type and in the typedef menu set the int64 to DWORD64 or your QWORD equivalent 
![image](https://cloud.githubusercontent.com/assets/994534/17779100/d6a2df5a-65a9-11e6-9765-b7b6fb3c9f89.png)

obviously this doesnt change the view type to unsigned, but should do for now
. will update when done adding

**Comment by dude719** [comment]
lmfao how did this get missed for so long

**Comment by stevemk14ebr** [comment]
Because DWORD64 is a QWORD: https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx

They are both unsigned 64 bit integers.

**Comment by Timboy67678** [comment]
have a look at https://github.com/dude719/Reclass-2015/commit/ae42cef3858814bcad915fe72011a0bd46d6ce51

@dude719 need u to make a cool icon for it btw
