### ISSUE TITLE
x64 Address entry is limited to 4 bytes

### ISSUE THREAD

**Issue by stevemk14ebr** [dude719/Reclass-2015#5]
In x64 mode the address entry bar (top left) is limited to 8 numbers or 4 bytes as each byte can have a value up to 0xFF (two numbers). To properly support x64 this bar should support numbers up to 16 characters long (8 bytes * 2 characters per byte), max value should be 0xFFFFFFFFFFFFFFFF (current is limited to 0xFFFFFFFF).

**Comment by dude719** [comment]
Embarrassing. I'll fix that when I'm home from vacation.

**Comment by stevemk14ebr** [comment]
it's been in reclass x64 for years so don't feel bad. I only discovered it a week ago when debugging VS project and address was greater than 32bits.
