### ISSUE TITLE
Using PCHAR on any valid (non-NULL-) pointer causes crash

### ISSUE THREAD

**Issue by Bueddl** [dude719/Reclass-2015#9]
The buffer allocation inside `ReadMemoryString` (see: [ReClass 2015/stdafx.cpp @ Line 93](https://github.com/dude719/Reclass-2015/blob/ab907b3c8b035fcb7c4e015a6ca7abb4d7ed4c6e/ReClass%202015/stdafx.cpp#L93)) seems one byte too small to me. There will be 64 bytes allocated and a read of the same size will be done afterwards. The problem reveals when placing the NULL-termination at `buffer[bytesRead]`, which is already outside the bounds of our buffer and will lead to application crash through heap corruption later on.

In my opinion the allocation should read
`auto buffer = std::make_unique<char[]>( max + 1 );`
instead of
`auto buffer = std::make_unique<char[]>( max );`

Handling NULL-pointers is not affected as the preceding call to `ReadMemory` will fail and branch into an alternative code path.

**Comment by dude719** [comment]
Thanks, nice catch! Will fix that up.
